export enum UserRole {
  REQUERENTE = 'REQUERENTE',
  REQUERIDO = 'REQUERIDO',
  ADVOGADO = 'ADVOGADO',
  ARBITRO = 'ARBITRO',
  ADMIN = 'ADMIN',
}

export enum ArbitragemStatus {
  AGUARDANDO_PAGAMENTO_REGISTRO = 'AGUARDANDO_PAGAMENTO_REGISTRO',
  AGUARDANDO_ACEITE = 'AGUARDANDO_ACEITE',
  RECUSADA = 'RECUSADA',
  AGUARDANDO_ASSINATURA = 'AGUARDANDO_ASSINATURA',
  AGUARDANDO_PAGAMENTO_TAXA = 'AGUARDANDO_PAGAMENTO_TAXA',
  EM_INSTRUCAO = 'EM_INSTRUCAO',
  AGUARDANDO_PETICAO = 'AGUARDANDO_PETICAO',
  AGUARDANDO_CONTESTACAO = 'AGUARDANDO_CONTESTACAO',
  ANALISE_PROVAS = 'ANALISE_PROVAS',
  AGUARDANDO_PROVAS_ADICIONAIS = 'AGUARDANDO_PROVAS_ADICIONAIS',
  GERANDO_SENTENCA = 'GERANDO_SENTENCA',
  SENTENCA_EM_REVISAO = 'SENTENCA_EM_REVISAO',
  SENTENCA_APROVADA = 'SENTENCA_APROVADA',
  SENTENCA_RATIFICADA = 'SENTENCA_RATIFICADA',
  ENCERRADA = 'ENCERRADA',
  CANCELADA = 'CANCELADA',
}

export enum CategoriaArbitragem {
  COMERCIAL = 'COMERCIAL',
  CONSUMIDOR = 'CONSUMIDOR',
  EMPRESARIAL = 'EMPRESARIAL',
  TRABALHISTA = 'TRABALHISTA',
  IMOBILIARIO = 'IMOBILIARIO',
  OUTROS = 'OUTROS',
}

export enum PecaTipo {
  PETICAO_INICIAL = 'PETICAO_INICIAL',
  CONTESTACAO = 'CONTESTACAO',
  REPLICA = 'REPLICA',
  TREPLICA = 'TREPLICA',
  ALEGACOES_FINAIS = 'ALEGACOES_FINAIS',
  OUTROS = 'OUTROS',
}

export enum ProvaTipo {
  DOCUMENTO = 'DOCUMENTO',
  IMAGEM = 'IMAGEM',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  PRINT = 'PRINT',
}

export enum SentencaStatus {
  RASCUNHO = 'RASCUNHO',
  EM_REVISAO = 'EM_REVISAO',
  APROVADA = 'APROVADA',
  RATIFICADA = 'RATIFICADA',
  PUBLICADA = 'PUBLICADA',
}

export enum CobrancaTipo {
  REGISTRO = 'REGISTRO',
  TAXA_ARBITRAL = 'TAXA_ARBITRAL',
  HONORARIOS = 'HONORARIOS',
}

export enum CobrancaStatus {
  PENDENTE = 'PENDENTE',
  PAGA = 'PAGA',
  VENCIDA = 'VENCIDA',
  CANCELADA = 'CANCELADA',
  REEMBOLSADA = 'REEMBOLSADA',
}

export enum PrazoTipo {
  ACEITE = 'ACEITE',
  ASSINATURA = 'ASSINATURA',
  PETICAO = 'PETICAO',
  CONTESTACAO = 'CONTESTACAO',
  PROVAS_ADICIONAIS = 'PROVAS_ADICIONAIS',
  REVISAO_SENTENCA = 'REVISAO_SENTENCA',
  RATIFICACAO = 'RATIFICACAO',
  CUSTOM = 'CUSTOM',
}

export enum PrazoStatus {
  ATIVO = 'ATIVO',
  CUMPRIDO = 'CUMPRIDO',
  EXPIRADO = 'EXPIRADO',
  CANCELADO = 'CANCELADO',
}
